name: backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi
  - uvicorn
  - sqlalchemy
  - psycopg2
  - pydantic
  - python-dotenv
  - mamba
  - pip
  - pip:
      - aiohttp
      - passlib
      - python-jose
      - pytest
